# https://docs.github.com/ja/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages
name: Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: "./.node-version"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Format Check
        run: npm run fmt:check
